Vagrant.configure("2") do |config|
    # common configs
    config.vm.box = "ubuntu/jammy64"
    #config.vm.provision "shell", path: "provision.sh"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 8
      vb.memory = "8192"
    end
  end
