apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: create-file
        image: busybox
        command: ["sh", "-c", "mkdir -p /usr/share/nginx/html && dd if=/dev/zero of=/usr/share/nginx/html/emptyfile.txt bs=1M count=10"]
        volumeMounts:
        - name: html-dir
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-dir
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-client
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: curl
    image: wbitt/network-multitool:latest
    command: ["bash", "-c", "sleep 5 && while true; do curl nginx-service.default.svc.cluster.local/emptyfile.txt -o foo; done"]
    #command: ["bash", "-c", "wget https://testfile.org/files-5GB-zip"]
    #command: ["bash", "-c", "sleep 999999"]
    securityContext:
      privileged: true
