Vagrant.configure("2") do |config|
    # common configs
    config.vm.box = "ig-kubecon-na-2024"

    # expose prometheus port
    config.vm.network "forwarded_port", guest: 9090, host: 9090
    # expose grafana port
    config.vm.network "forwarded_port", guest: 3000, host: 3000

    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Update this according to your machine
      vb.cpus = 8
      vb.memory = "8192"
    end
  end
