apiVersion: 1
kind: instance-spec
image: trace_exec:latest
name: alert-bad-process
paramValues:
  # monitor all namespaces
  operator.KubeManager.all-namespaces: true
  # monitor shell executions (only bash on this example)
  operator.filter.filter: proc.comm==bash
  # name of the metric to export
  operator.otel-metrics.otel-metrics-name: 'exec:shell_executions'
  # annotate gadget to enable metrics collection
  # why is it now working?
  #operator.oci.annotate: bar
